.github/workflows/ci.yml, .idea/misc.xml, RELEASING.md, extracare-gradle-plugin/build.gradle, sample-android/build.gradle, sample/build.gradle
Remove "extracare-gradle-plugin" which is already implied. Now the plugin name is simpler:
```groovy
apply plugin: 'dev.drewhamilton.extracare'
```
=> Update Gradle plugin ID

extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/codegen/EqualsGenerator.kt, extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/codegen/HashCodeGenerator.kt, extracare-compiler-plugin/src/test/kotlin/dev/drewhamilton/extracare/ExtraCarePluginTest.kt, sample/src/main/kotlin/dev/drewhamilton/extracare/sample/Complex.kt, sample/src/main/kotlin/dev/drewhamilton/extracare/sample/alt/DataComplex.kt, sample/src/test/kotlin/dev/drewhamilton/extracare/sample/ComplexTest.kt
=> Fix compilation with long members

.github/workflows/release.yml, README.md, RELEASING.md, extracare-gradle-plugin/gradle/wrapper/gradle-wrapper.properties, gradle.properties, gradle/wrapper/gradle-wrapper.properties, publish.gradle
Publish automatically from master branch
=> Automate publication

extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/codegen/ToStringGenerator.kt, gradle.properties
Update ToStringGenerator for breaking changes in 1.4.20. Closes #18.
=> Kotlin 1.4.21

.github/workflows/ci.yml, build.gradle, extracare-compiler-plugin/src/test/kotlin/dev/drewhamilton/extracare/ExtraCarePluginTest.kt, extracare-gradle-plugin/build.gradle
Test on CI with Java versions 8, 11, 12, 13, 14, and 15
=> Add ability to test with different JVM compiler versions

extracare-gradle-plugin/src/main/kotlin/dev/drewhamilton/extracare/gradle/ExtraCareGradlePlugin.kt, extracare-gradle-plugin/src/main/kotlin/dev/drewhamilton/extracare/gradle/ExtraCarePluginExtension.kt
=> Modernize Gradle plugin extension

extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/codegen/EqualsGenerator.kt, gradle.properties
Closes #28. Will require another breaking release.
=> Kotlin 1.4.30

.github/workflows/ci.yml, extracare-gradle-plugin/src/main/kotlin/dev/drewhamilton/extracare/gradle/ExtraCareGradlePlugin.kt, gradle.properties
Previously, changed Gradle API did not trigger failure
=> Ensure build runs with checks for Gradle plugin in CI

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/codegen/PokoCodegenExtension.kt, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt, poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt, poko-compiler-plugin/src/test/resources/illegal/NoConstructorProperties.kt
=> Ensure failure for no primary constructor properties

sample/gradle.properties
=> Compose 1.0.0-beta05

build.gradle, gradle.properties, sample/build.gradle
Remove dependencies on JCenter and Bintray repositories
=> Dokka 1.4.32

.github/workflows/ci.yml, README.md, RELEASING.md, gradle.properties, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt, sample/build.gradle
Will keep this open as a draft until 1.5 stable is released.
Changes:
* Remove references to WrappedVariableDescriptor
=> Kotlin 1.5

build.gradle, gradle.properties, gradle/libs.versions.toml, poko-annotations/build.gradle, poko-compiler-plugin/build.gradle, poko-gradle-plugin/build.gradle, sample/build.gradle, sample/gradle.properties, sample/settings.gradle, settings.gradle
Use Gradle's new version catalogs feature to organize dependencies
=> Version catalogs

.github/workflows/release.yml, gradle.properties, poko-gradle-plugin/build.gradle, publish.gradle
=> Fix marker pom

gradle/libs.versions.toml
=> Compose 1.0.0-rc01

.idea/misc.xml, sample/build.gradle, sample/settings.gradle
IDE update, Android build tools version, correct use of local.properties in sample project
=> Small updates

.idea/codeStyles/Project.xml, gradle/libs.versions.toml, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt, sample/gradle.properties
=> Kotlin 1.6

.idea/misc.xml, README.md, gradle/libs.versions.toml, sample/build.gradle
Compile with Kotlin 1.6.10. Also bump Compose test version.
=> Kotlin 1.6.10

build.gradle, gradle/libs.versions.toml, sample/build.gradle
Also updates to Compose and AGP in the sample project
=> Kotlin 1.6.20-RC

gradle/libs.versions.toml
* Compose compiler & runtime 1.2.0-beta02
* KSP 1.6.21-1.0.5
* AGP 7.2.0
=> Kotlin 1.6.21

.github/workflows/ci.yml
Already updated the build job and the release job
=> Ensure the build-sample job on CI uses the Zulu JDK distribution

.github/workflows/ci.yml, .github/workflows/release.yml, poko-compiler-plugin/build.gradle
Run tests on 8 through 17 as well
=> Compile with Java 18

gradle/libs.versions.toml
Also Compose runtime 1.2.0-rc03
=> Test with Compose compiler 1.2.0

gradle/libs.versions.toml, poko-compiler-plugin/api/poko-compiler-plugin.api
* KSP 1.7.20-1.0.6
* Test with Compose compiler 1.3.2
* Test with Compose runtime 1.2.1
=> Kotlin 1.7.20

renovate.json5
They are tightly coupled so should be updated together.
=> Group Kotlin compiler tools together for Renovate

.github/workflows/ci.yml, .github/workflows/release.yml, poko-compiler-plugin/build.gradle.kts
Add one more task to ensure version 8 through 18 are also tested
=> Build on CI with JDK 19

gradle/libs.versions.toml, sample/compose/build.gradle.kts
=> Reference Compose compiler package in libs.versions.toml

.idea/kotlinc.xml, build.gradle.kts, poko-annotations/build.gradle.kts, poko-compiler-plugin/build.gradle.kts, poko-gradle-plugin/build.gradle.kts, sample/build.gradle.kts, sample/compose/build.gradle.kts, sample/jvm/build.gradle.kts
There were a number of suppressions waiting on Gradle 8.1 and AGP 8.0 that could now be removed. Also updates an IDE file.
=> Clean up build files

.idea/codeStyles/Project.xml, poko-annotations/src/main/kotlin/dev/drewhamilton/poko/Poko.kt, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoIrGenerationExtension.kt, poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/PokoGradlePlugin.kt, sample/compose/src/main/kotlin/dev/drewhamilton/poko/sample/compose/Poko.kt, sample/jvm/src/main/kotlin/dev/drewhamilton/poko/sample/jvm/Poko.kt, sample/jvm/src/test/kotlin/dev/drewhamilton/poko/sample/jvm/SampleTest.kt, sample/jvm/src/test/kotlin/dev/drewhamilton/poko/sample/jvm/arrays/ArrayTest.kt
Comments were too wide to read on web on a smallish screen.
=> Update code style to 100 width

.github/workflows/ci.yml, .github/workflows/release.yml
It can cross-compile the Linux and Windows targets for Kotlin multiplatform.
=> Switch CI to use MacOS

gradle/libs.versions.toml
=> Compose compiler 1.5.2

README.md
=> Remove multiplatform TODO

renovate.json5
This should combine #273 and #274, which are broken as separate PRs, into a single PR.
=> Group upload and download artifact actions together

gradle/libs.versions.toml
Using Kotlin 2 as base branch.
=> KSP 2.0.0-Beta2-1.0.16

gradle/libs.versions.toml
Bump compose compiler in K2 branch
=> Compose compiler 1.5.8-dev-k2.0.0-Beta2-99ed868a0f8

.github/workflows/ci.yml, .github/workflows/release.yml
`gradle/gradle-build-action` is deprecated.
=> Switch to `gradle/actions/setup-gradle@v3` on CI

poko-annotations/build.gradle.kts, poko-tests/build.gradle.kts
Android native targets support for #335
=> Add Android native targets

build.gradle.kts
=> Remove unused imports

.github/workflows/ci.yml, .github/workflows/release.yml
This is now supported by Gradle 8.8.
=> Build with JDK 22

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt
Kotlin 2.0.20-Beta1 breaks the binary signature of two compiler APIs. Rather than breaking Poko as usual, I'm going to attempt to maintain compatibility by using reflection to access broken APIs. Not sure how maintainable it will be in the long run, but it's worth a try.
Fixes #363.
=> Implement reflection fallbacks for two incompatible functions

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
Addresses @lupuuss's [comment](https://github.com/drewhamilton/Poko/issues/363#issuecomment-2221028453) on #363.
=> Implement reflective compatibility with 2.0.20-Beta2

gradle/libs.versions.toml, kotlin-js-store/yarn.lock
Update 2.0.20 branch to 2.0.20 final.
=> Update Kotlin 2.0.20 branch to 2.0.20 final

.github/workflows/ci.yml, .idea/kotlinc.xml, README.md, gradle/libs.versions.toml, kotlin-js-store/yarn.lock, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt, sample/kotlin-js-store/yarn.lock
Maintains compatibility with 2.0.0 via reflection.
=> Kotlin 2.0.20

README.md
=> Include signing info in README.md

.gitignore, poko-gradle-plugin/build.gradle.kts
=> Enable stricter validation for Gradle plugin

.github/workflows/ci.yml, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirCheckersExtension.kt, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/compat.kt, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt
Redo of #524, except it shouldn't be merged when it fails.
=> Test Kotlin 2.2.0-Beta2

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirCheckersExtension.kt
Was pointed to this in kotlin-lang as a fix, rather than using the raw PsiElement class. Ref: https://kotlinlang.slack.com/archives/C7L3JB43G/p1759734640128339?thread_ts=1759722235.490679&cid=C7L3JB43G
=> Use KtElement instead of class workaround

.github/workflows/ci.yml, poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt
=> Test forward compatibility with Kotlin 2.2.21-RC and 2.3.0-Beta1
