drewhamilton/Poko

extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/DataApiCodegenExtension.kt
extracare-compiler-plugin/src/test/kotlin/dev/drewhamilton/extracare/ExtraCarePluginTest.kt
sample/src/main/kotlin/dev/drewhamilton/extracare/sample/explicit/ChildOfExplicitFunctionDeclarations.kt
sample/src/main/kotlin/dev/drewhamilton/extracare/sample/explicit/ExplicitFunctionDeclarations.kt
sample/src/main/kotlin/dev/drewhamilton/extracare/sample/explicit/SuperExplicitFunctionDeclarations.kt
sample/src/test/kotlin/dev/drewhamilton/extracare/sample/explicit/ChildOfExplicitFunctionDeclarationsTest.kt
sample/src/test/kotlin/dev/drewhamilton/extracare/sample/explicit/DataChildOfExplicitFunctionDeclarations.kt
sample/src/test/kotlin/dev/drewhamilton/extracare/sample/explicit/ExplicitFunctionDeclarationsTest.kt

Fixes #11.
Behaves like data classes: Does not generate these functions if and only if they are explicitly declared directly in the `@DataApi` class. Overrides any explicit declarations in parent classes.

Allow explicit toString/equals/hashCode

---

build.gradle
data-api-annotations/api/data-api-annotations.api
extracare-compiler-plugin/api/extracare-compiler-plugin.api
extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/CompilerOptions.kt
extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/ExtraCareCommandLineProcessor.kt
extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/ExtraCareComponentRegistrar.kt
extracare-gradle-plugin/api/extracare-gradle-plugin.api
extracare-gradle-plugin/build.gradle
gradle.properties
sample/build.gradle

Add Kotlin's binary compatibility validator to be aware of breaking changes going forward. Make minor refactors to minimize public API.

Binary compatibility validation

---

extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/Annotation.kt
extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/CompilerOptions.kt
extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/ExtraCareCommandLineProcessor.kt
extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/ExtraCareComponentRegistrar.kt
extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/codegen/DataApiCodegenExtension.kt
extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/ir/DataApiIrGenerationExtension.kt
extracare-compiler-plugin/src/main/kotlin/dev/drewhamilton/extracare/ir/DataApiMembersTransformer.kt
extracare-compiler-plugin/src/test/kotlin/dev/drewhamilton/extracare/ExtraCarePluginTest.kt
extracare-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
extracare-gradle-plugin/src/main/kotlin/dev/drewhamilton/extracare/gradle/ExtraCareGradlePlugin.kt
extracare-gradle-plugin/src/main/kotlin/dev/drewhamilton/extracare/gradle/ExtraCarePluginExtension.kt
sample/build.gradle
sample/src/main/kotlin/dev/drewhamilton/extracare/sample/Poko.kt
sample/src/main/kotlin/dev/drewhamilton/extracare/sample/Sample.kt

Closes #29.
In the `extraCare` configuration block, consumers can set whatever class they choose as the data API annotation:
```groovy
extraCare {
dataApiAnnotation.set 'com.example.GeneratedEqualsAndToString'
}
```
```kotlin
@GeneratedEqualsAndToString class DataModel(val id: String)
```

Support custom annotations

---

build.gradle
poko-compiler-plugin/build.gradle
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoComponentRegistrar.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt

Fixes #35.
Remove internal use of `IrPluginContext.symbolTable` which returns unbound symbols. Replace with call directly to `IrPluginContext.referenceFunctions` using `FqName` of the desired function symbol.

Compose fix

---

.github/workflows/ci.yml
.gitignore
.idea/codeStyles/Project.xml
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
sample/build.gradle
sample/gradle.properties
sample/src/main/AndroidManifest.xml

Fixes another unbound symbol problem that was breaking Poko+Compose.
Also add a testing setup for Compose, since this is the second time this happened. Now we can bump the Compose and AGP versions each time either is released to verify Poko still works with Compose.

Fix Jetpack Compose support

---

poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/PokoGradlePlugin.kt

Previously was `compileOnly`. This did not get applied to test configurations of projects using Poko, which meant developers had to manually import the annotation anyway. As `implementation` it will get included in all configurations.
Consumers can still use a custom annotation if they'd like to use `compileOnly`.

Add Poko annotation as `implementation` dependency

---

.github/workflows/ci.yml
build.gradle
gradle.properties
poko-compiler-plugin/build.gradle
poko-gradle-plugin/build.gradle

Internally, use `kapt` instead of `ksp` because `kapt` doesn't work with Java 16

Add Java 16 to CI

---

.github/workflows/ci.yml
RELEASING.md
gradle/libs.versions.toml
sample/build.gradle

Uses Compose 1.0.0-SNAPSHOT to test against a Kotlin 1.5.0-supporting version before its beta release

Re-enable Compose CI

---

gradle/libs.versions.toml
sample/build.gradle
sample/gradle.properties

First release supporting Kotlin 1.5, so use of snapshots is dropped. Updates to Kotlin 1.5.10.

Compose UI 1.0.0-beta08

---

.github/workflows/release.yml
gradle.properties

Run `publishAllPublications` instead of just `publishReleasePublication` during release Action

---

README.md
gradle/libs.versions.toml
sample/build.gradle

Also enables Jetpack Compose test builds to work when Compose's Kotlin version is lagging behind Poko's, by compiling only the Compose module with that different Kotlin version. Bumps to Compose 1.0.0-rc02.

Kotlin 1.5.21

---

gradle/libs.versions.toml

Update to non-beta versions of Jetpack Compose and AGP, used for testing the sample module.

Compose 1.0.1

---

.github/workflows/ci.yml
gradle.properties
gradle/libs.versions.toml
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-compiler-plugin/src/test/resources/illegal/Value.kt
sample/build.gradle
sample/gradle.properties

Bumps Kotlin to 1.7.0-RC and related dependencies accordingly. Inline classes are removed, so value classes are disallowed instead.
Fixes #75.

Kotlin 1.7.0-RC

---

build.gradle
info.gradle
poko-compiler-plugin/build.gradle
poko-gradle-plugin/build.gradle
sample/jvm/build.gradle
sample/settings.gradle
settings.gradle

* Remove/update deprecated Gradle features
* Avoid imports that the IDE doesn't like
* Differentiate repetitive logs
* Connect dependent tasks

Clean up Gradle warnings

---

gradle/libs.versions.toml

With test dependency updates:
* Compose compiler 1.2.0-dev-k1.7.0-RC-4a641765aa6
* Compose runtime 1.2.0-beta03

Kotlin 1.7.0-RC2

---

.idea/kotlinc.xml
gradle/libs.versions.toml
poko-compiler-plugin/build.gradle
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCommandLineProcessor.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoComponentRegistrar.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoIrGenerationExtension.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt

Kotlin 1.8's compiler comes with a host of new opt-in annotations, mostly related to the upcoming migration to FIR & K2. For now I've just propagated the opt-in annotations. I probably won't need to implement these changes in this PR, but I'll need to soon.

Kotlin 1.8

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoComponentRegistrar.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoIrGenerationExtension.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/Annotations.kt
poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/PokoGradlePlugin.kt
poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/PokoPluginExtension.kt

The annotation used to denote Poko classes can be customized. This changes the format of the input string, using `/` rather than `.` to denote nested package names.
For consumers,
```groovy
pokoAnnotation.set "com.example.OuterClass.InnerAnnotation"
```
changes to
```groovy
pokoAnnotation.set "com/example/OuterClass.InnerAnnotation"
```
This also removes automatically adding the legacy `DataApi` dependency – consumers will have to add it manually if using it.

Change annotation arg format

---

poko-compiler-plugin/api/poko-compiler-plugin.api
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt

One step of supporting FIR and K2.

Replace `ComponentRegistrar` with `CompilerPluginRegistrar`

---

gradle/libs.versions.toml
poko-compiler-plugin/build.gradle.kts

Switches back to the non-fork now that it supports Kotlin 1.8

Kotlin Compile Testing 1.5.0

---

sample/compose/build.gradle.kts
sample/compose/src/main/AndroidManifest.xml

* Update `PokoSample:compose` AGP-related syntax
* Fix mismatch in `PokoSample:compose` javac/kotlinc targets due to AGP bug

Fix CI warnings for `PokoSample:compose`

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoIrGenerationExtension.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt

Bring generation logic up-to-date with the Kotlin compiler's internal data class generation logic, which has changed somewhat over the last several Kotlin versions. Reduces usage of "descriptors" though does not eliminate it entirely. Removes the need for `@FirIncompatiblePluginAPI`.

Update generation logic

---

.github/workflows/ci.yml
.github/workflows/release.yml

Enables caching between builds

Use gradle-build-action for Gradle tasks on CI

---

renovate.json5

As visible in #104, Renovate provides strange versions for these 3 packages. They should be lined up with the shared `kotlin` version, so ignoring them should produce the desired behavior from Renovate.

Renovate: Ignore Kotlin packages with unsupported versions

---

.idea/kotlinScripting.xml
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt

I think these calls won't be compatible with K2. This makes sure more aren't added under the class-level opt-in, and gives context for why they're used in each case.

Move `@ObsoleteDescriptorBasedAPI` opt-in to specific call sites

---

poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-compiler-plugin/src/test/resources/api/SimpleWithExtraParam.kt

This behavior has been around since the start but I didn't have tests for it. I want to make sure I know if it's broken during K2 migration.

Add tests for ignored non-property constructor parameter

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt

In favor of `owner` access. Reduces use of obsolete APIs.

Remove descriptor access to receiver parameters

---

poko-compiler-plugin/build.gradle.kts

It's been super flaky for awhile now. Flakiness is not dependent on JDK distribution: see #149.

Skip testJdk10 on CI

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt

Had stale string references to `@ReadArrayContent`; annotation is now named `@ArrayContentBased`.

Update annotation name referenced in array content error message

---

poko-compiler-plugin/build.gradle.kts
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/logging.kt

Start to improve the readability of the generation code by extracting the shared helpers that will be used by each of the to-be-extracted `equals`, `hashCode`, and `toString` generation helpers.

Extract shared generation helpers from PokoMembersTransformer

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt

#1 part 4b: Implements support for properties of type `Any?` that turn out to be `BooleanArray`s at runtime.
Refactors the existing typed array helpers to be easy to reuse. All other primitive types can now be an easy fast-follow to this.
Does not implement the same support for generic properties: I'll add that separately.

Runtime boolean array support

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt

#1 part 4c: Implements support for properties of type `Any?` that turn out to be any primitive array type at runtime.
Does not implement the same support for generic properties: I'll add that separately.

Runtime primitive array support

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-compiler-plugin/src/test/resources/api/ComplexGenericArrayHolder.kt
poko-compiler-plugin/src/test/resources/api/GenericArrayHolder.kt

#1 part 4d: Implements `@ArrayContentBased` support for properties with a generic type (e.g. `T`) that turn out to be arrays at runtime.

Runtime array support for generic properties

---

CHANGELOG.md
README.md
poko-annotations/api/poko-annotations.api
poko-annotations/src/main/kotlin/dev/drewhamilton/poko/ArrayContentBased.kt
poko-annotations/src/main/kotlin/dev/drewhamilton/poko/ArrayContentSupport.kt
poko-compiler-plugin/src/test/resources/api/AnyArrayHolder.kt
poko-compiler-plugin/src/test/resources/api/ArrayHolder.kt
poko-compiler-plugin/src/test/resources/api/ComplexGenericArrayHolder.kt
poko-compiler-plugin/src/test/resources/api/GenericArrayHolder.kt
poko-compiler-plugin/src/test/resources/illegal/GenericArrayHolder.kt
poko-compiler-plugin/src/test/resources/illegal/NotArrayHolder.kt
poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/PokoPluginExtension.kt

Updates documentation for the new `@ArrayContentBased` annotation, adding it to the readme and the changelog.
Also renames the opt-in annotation to `@ArrayContentSupport` for brevity.
Closes #1.

Update array content documentation

---

gradle/libs.versions.toml
poko-gradle-plugin/build.gradle.kts

Consumers of poko-gradle-plugin are plugging Poko into a Kotlin compilation, not the other way around. They are expected to apply kotlin-gradle-plugin independently, rather than relying on Poko to pull it in. It's very unlikely that any Poko consumers are not already doing this.
Practically speaking, the goal of this is to ensure that consumers using a compatible version of Kotlin older than the one used to compile Poko are not forced to a newer version. For example, projects compiling with Kotlin 1.8.21 should be able to use Poko 0.13.2 without being forced to Kotlin 1.8.22.

Change Kotlin compiler dependency to compileOnly

---

poko-annotations/src/main/kotlin/dev/drewhamilton/poko/ArrayContentBased.kt
poko-annotations/src/main/kotlin/dev/drewhamilton/poko/Poko.kt
poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/PokoGradlePlugin.kt

Implements #163 (don't want to close until I decide whether to revert this). Converts the default `@Poko` annotation from binary retention to source retention, and adds the poko-annotations dependency as `compileOnly` by default, rather than `implementation`. This makes Poko invisible to consumers of libraries using Poko.
A downside is that such consumers will see `@Poko` ~~highlighted in red~~ (edit: in neutral color) in their IDEs, and won't be able to click through to its doc comments.

Source retention

---

gradle/libs.versions.toml
poko-compiler-plugin/build.gradle.kts
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-gradle-plugin/build.gradle.kts
sample/compose/build.gradle.kts
sample/compose/src/test/kotlin/dev/drewhamilton/poko/sample/compose/SampleTest.kt
sample/jvm/build.gradle.kts
sample/jvm/src/test/kotlin/dev/drewhamilton/poko/sample/jvm/SampleTest.kt
sample/jvm/src/test/kotlin/dev/drewhamilton/poko/sample/jvm/arrays/ArrayTest.kt

It has Truth-like API but supports the forthcoming multiplatform migration where Truth is only a JVM/Android library.
Refs #142

Migrate to AssertK

---

poko-gradle-plugin/build.gradle.kts

Remove KSP from Gradle plugin

---

buildSrc/src/main/java/dev/drewhamilton/poko/build/info.kt
poko-compiler-plugin/build.gradle.kts
poko-gradle-plugin/build.gradle.kts

Remove automatic task wiring in favor of implicit wiring by adding the `Copy` task directly as a source folder. Gradle will interrogate the task for its `@OutputDirectory` and add that as a source folder along with a dependency on the task for anyone who consumes the source folders.

Simplify setup of `ArtifactInfo` template copy

---

sample/compose/build.gradle.kts

Before:
$ gw -p sample :compose:build --dry-run --console=plain | grep SKIPPED | wc -l
89
After deleting redundant disabling:
$ gw -p sample :compose:build --dry-run --console=plain | grep SKIPPED | wc -l
89
After adding `androidResources = false`:
$ gw -p sample :compose:build --dry-run --console=plain | grep SKIPPED | wc -l
76

Remove redundant feature disabling and add one more

---

.github/workflows/ci.yml

The main project build needs MacOS now to support all targets (#179), but the sample is still JVM-only for now. That will change soon, but until then we may as well retain the high parallelism that GitHub allows for Ubuntu machines.

Revert CI build-sample to Ubuntu

---

renovate.json5

We don't want weird versions like #185. Renovate is already using the regular Kotlin version for this (and the other ignored Kotlin-related deps).

Add stdlib to dependencies ignored by Renovate

---

artifact-info-template/ArtifactInfo.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCommandLineProcessor.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt
poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/Annotations.kt
poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/PokoGradlePlugin.kt
poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/PokoPluginExtension.kt

Default enabled to true and the annotation to the built-in one.
This is useful for the future 'poko-tests' module where I want to apply the Kotlin compiler plugin solely through the `dependencies { }` and shouldn't need to pass arguments. It also matches the behavior when used through the Gradle plugin.

Allow compiler plugin to be used without arguments

---

build-support/src/main/java/dev/drewhamilton/poko/build/PokoBuildPlugin.kt
build.gradle.kts

I'm adding a `poko-tests` module whose main source set holds the test classes and those test source set does the assertions on them. This new module should not have its ABI validated. Also if we move the samples into the main build (not strictly required, actually) they shouldn't have their ABI validated.
Proof it still works:
```
$ gb --dry-run --console=plain | \grep -i apicheck
:poko-annotations:jvmApiCheck SKIPPED
:poko-annotations:apiCheck SKIPPED
:poko-compiler-plugin:apiCheck SKIPPED
:poko-gradle-plugin:apiCheck SKIPPED
```

Only do binary validation on published modules

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt

Use built-in isValue property to determine value class. Do not conditionally check for value class when generating equals as they are unsupported.

Small IR updates

---

.github/workflows/ci.yml
poko-compiler-plugin/build.gradle.kts

The OpenJDK itself has no concept of LTS, so any vendor is welcome to deem _any_ version an LTS version, but in general they all follow Oracle's lead with 8, 11, 17, and soon 21. These become a representative sample that covers the overwhelming majority of deployments, and thus should be sufficient for test coverage.
Closes #96

Only test on older JDKs which are commonly LTS

---

poko-tests/src/commonTest/kotlin/AnyArrayHolderTest.kt
poko-tests/src/commonTest/kotlin/ArrayHolderTest.kt
poko-tests/src/commonTest/kotlin/ComplexTest.kt
poko-tests/src/commonTest/kotlin/ExplicitDeclarationsTest.kt
poko-tests/src/commonTest/kotlin/GenericArrayHolderTest.kt
poko-tests/src/commonTest/kotlin/NestedTest.kt
poko-tests/src/commonTest/kotlin/SimpleTest.kt
poko-tests/src/commonTest/kotlin/SimpleWithExtraParamTest.kt
poko-tests/src/commonTest/kotlin/SuperclassDeclarationsTest.kt

Still more we could do here, like add a `isSymmetricallyEqualTo()` helper to eliminate the double a equals b/b equals a checks.

Use more features of AssertK

---

poko-tests/src/commonMain/kotlin/poko/ComplexGenericArrayHolder.kt
poko-tests/src/commonTest/kotlin/ComplexGenericArrayHolderTest.kt

Accidentally dropped this when migrating `AnyArrayHolder`.
Closes #180

Migrate `ComplexGenericArrayHolder` test

---

poko-compiler-plugin/build.gradle.kts
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-tests/build.gradle.kts

Now that the majority of the tests have migrated from the compiler module to a dedicated integration test module the JDK test variance needs to move as well. Thankfully, Kotlin makes this relatively simple.

Vary the integration test JDK toolchains

---

gradle/libs.versions.toml
poko-compiler-plugin/build.gradle.kts
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/asm.kt

An integer is its own `hashCode`, and the function is documented to simply return the input on the JVM. For JS and native the behavior is the same: https://github.com/JetBrains/kotlin/blob/1.9.0/kotlin-native/runtime/src/main/kotlin/kotlin/Primitives.kt#L1353.
Saves at least 3 bytes per property within the function bytecode, not counting any effects on things like the constant pool (for JVM).
Before:
public int hashCode();
Code:
0: aload_0
1: getfield      #23                 // Field int:I
4: invokestatic  #50                 // Method java/lang/Integer.hashCode:(I)I
7: istore_1
8: iload_1
9: bipush        31
11: imul
⋮
46: ireturn
After:
public int hashCode();
Code:
0: aload_0
1: getfield      #23                 // Field int:I
4: istore_1
5: iload_1
6: bipush        31
8: imul
⋮
43: …

Integer fast-path for `hashCode` calculation

---

gradle/libs.versions.toml
poko-compiler-plugin/build.gradle.kts
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-compiler-plugin/src/test/resources/illegal/NoConstructorProperties.kt
poko-tests/build.gradle.kts
poko-tests/src/commonTest/kotlin/GenericArrayHolderTest.kt

Closes #118. Poko now works for Kotlin language version 2.0 (and continues to work for 1.9).

Support K2

---

poko-compiler-plugin/build.gradle.kts
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-tests/performance/build.gradle.kts
poko-tests/performance/src/test/kotlin/JvmPerformanceTest.kt
poko-tests/performance/src/test/kotlin/asm.kt
poko-tests/performance/src/test/kotlin/sources.kt
poko-tests/src/commonMain/kotlin/performance/IntAndLong.kt
settings.gradle.kts

This will open up the ability to assert on JS and native which simply isn't possible with the Kotlin Compiler Testing infrastructure.

Migrate performance tests to occur on tests project

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-tests/build.gradle.kts
poko-tests/performance/build.gradle.kts
poko-tests/performance/src/test/kotlin/JsPerformanceTest.kt
poko-tests/performance/src/test/kotlin/sources.kt
poko-tests/src/commonMain/kotlin/performance/Main.kt

Before:
```js
protoOf(IntAndLong).equals = function (other) {
if (this === other)
return true;
if (!(other instanceof IntAndLong))
return false;
var tmp0_other_with_cast = other instanceof IntAndLong ? other : THROW_CCE();
if (!(this.v_1 === tmp0_other_with_cast.v_1))
return false;
if (!this.w_1.equals(tmp0_other_with_cast.w_1))
return false;
return true;
};
```
After:
```js
protoOf(IntAndLong).equals = function (other) {
if (this === other)
return true;
if (!(other instanceof IntAndLong))
return false;
if (!(this.v_1 === other.v_1))
return false;
if (!this.w_1.equals(other.w_1))
return false;
return true;
};
```
Refs #204

Eliminate redundant instanceof check in JS output

---

build.gradle.kts
poko-tests/performance/build.gradle.kts
poko-tests/performance/src/test/kotlin/JvmPerformanceTest.kt
poko-tests/performance/src/test/kotlin/sources.kt

Just ensuring we don't regress this performance-related optimization by accident.

Test that JDKs newer than 8 use `invokedynamic` for `toString`

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-tests/performance/src/test/kotlin/JvmPerformanceTest.kt
poko-tests/src/commonMain/kotlin/performance/UIntAndLong.kt

It is backed by an `Int` whose `hashCode` is the identity function.
Before:
public int hashCode();
Code:
0: aload_0
1: getfield      #13                 // Field uint:I
4: invokestatic  #35                 // Method kotlin/UInt."hashCode-impl":(I)I
7: istore_1
8: iload_1
9: bipush        31
11: imul
12: aload_0
13: getfield      #17                 // Field long:J
16: invokestatic  #40                 // Method java/lang/Long.hashCode:(J)I
19: iadd
20: istore_1
21: iload_1
22: ireturn
After:
public int hashCode();
Code:
0: aload_0
1: getfield      #13                 // Field uint:I
4: istore_1
5: iload_1
6: bipush        31
8: imul
9: aload_0
10: getfield      #17                 // Field long:J
13: invokestatic  #34                 // Method java/lang/Long.hashCode:(J)I
16: iadd
17: …

Do not invoke `hashCode` for `UInt`

---

poko-tests/src/commonTest/kotlin/ComplexTest.kt

Compares `poko.Complex` to `data.Complex`, ensuring Poko produces calculations equivalent to data classes. These were accidentally dropped in #209.

Re-add dropped tests of complex Poko class

---

poko-tests/src/commonMain/kotlin/data/Complex.kt
poko-tests/src/commonMain/kotlin/poko/Complex.kt
poko-tests/src/commonTest/kotlin/ComplexTest.kt

I think this is failing because of the previous behavior of [KT-62383](https://youtrack.jetbrains.com/issue/KT-62383), and thus depends on #233. Apparently we've had different `hashCode` values from data classes when boolean properties are involved. Oops!

Test boolean properties in ComplexTest

---

.github/workflows/ci.yml
.github/workflows/gradle-wrapper.yml

As recommended by Jake in #260.
I guess the downside is that the new Action can't be used in a branch protection rule because it doesn't always run. Leaving the validation in `release.yml` out of an abundance of caution.

Move Gradle wrapper validation to standalone Action

---

build.gradle.kts
poko-annotations/build.gradle.kts
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt
poko-tests/build.gradle.kts

Closes #235.
Adds the `wasmJs` target to the `:poko-annotations` and `:poko-tests` projects.
Adds explicit `irImplicitCast` calls after `irIs` checks to avoid compile errors: the WASM target doesn't generate these automatically like other targets do. I posted a public Slack message about it [here](https://kotlinlang.slack.com/archives/C7L3JB43G/p1702592212316199).
The WASM target currently requires a canary Node.js version. I'm unclear on the implications of shipping with this, will follow up in this PR's comments.

Support WASM

---

RELEASING.md
artifact-info-template/ArtifactInfo.kt
build-support/build.gradle.kts
build-support/src/main/java/dev/drewhamilton/poko/build/PokoBuildExtension.kt
build-support/src/main/java/dev/drewhamilton/poko/build/PokoBuildPlugin.kt
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
poko-annotations/build.gradle.kts
poko-annotations/gradle.properties
poko-compiler-plugin/build.gradle.kts
poko-compiler-plugin/gradle.properties
poko-gradle-plugin/build.gradle.kts
poko-gradle-plugin/gradle.properties
sample/build.gradle.kts
sample/properties.gradle
sample/settings.gradle.kts

Revives and finishes #188. Moves all publication settings into the build support plugin except for the group and version. These are currently both needed in `gradle.properties` so they can be read by both the main project and the sample. The build support plugin now manually reads these from `gradle.properties` and passes them to the publish plugin.

Move publishing configuration mostly into the build support plugin

---

settings.gradle.kts

Sets up toolchain download repositories when a JDK needs to be downloaded by the build

Apply Foojay Toolchains Plugin

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt

Revives #205. The class generated by them is now filtered out of the binary compatibility validator's output.
> $EntriesMappings classes backing Kotlin's 1.9 Enum.entries are now filtered out (Kotlin/binary-compatibility-validator#144)

Use `entries` property on enums

---

.github/workflows/ci.yml
poko-tests/build.gradle.kts
poko-tests/performance/build.gradle.kts
poko-tests/performance/src/test/kotlin/JvmPerformanceTest.kt
poko-tests/performance/src/test/kotlin/asm.kt
poko-tests/performance/src/test/kotlin/sources.kt

From my understanding of the errors on #258, calling `jvmToolchain` per-compilation in Kotlin Multiplatform is [disallowed in Kotlin 2](https://youtrack.jetbrains.com/issue/KT-64629/Gradle-configuration-fails-fun-jvmToolchainjdkVersion-Int-Unit-cant-be-called-in-this-context-by-implicit-receiver). This alternative makes the CI less efficient by needing to spin up more machines, but hopefully doesn't make it slower since the new machines are Ubuntu and will run in parallel to the main build. Happy to change the approach if there's a better way.

Set `:poko-tests` JVM toolchain version via CI

---

build.gradle.kts

Per [Jake's blog post](https://jakewharton.com/kotlins-jdk-release-compatibility-flag/).

Add `-Xjdk-release` flag to released modules

---

.idea/kotlinc.xml
gradle/libs.versions.toml
kotlin-js-store/yarn.lock
sample/compose/build.gradle.kts
sample/kotlin-js-store/yarn.lock

Target branch drew/kotlin-2.0.
androidx-compose-compiler hasn't been built against 2.0.0-RC1 but tests pass locally (except the ones that are expected to fail on Windows).

Kotlin 2.0.0-RC1

---

build.gradle.kts

Use Kotlin's default Node version

---

.github/workflows/ci.yml
.github/workflows/release.yml

Gradle 8.7 doesn't technically support being run with Java 22, but maybe it'll work anyway. Otherwise this can wait for the next Gradle release.

Compile with JDK 22

---

poko-annotations/src/commonMain/kotlin/dev/drewhamilton/poko/ArrayContentBased.kt
poko-annotations/src/commonMain/kotlin/dev/drewhamilton/poko/ArrayContentSupport.kt
poko-compiler-plugin/src/test/resources/illegal/GenericArrayHolder.kt
poko-compiler-plugin/src/test/resources/illegal/NotArrayHolder.kt
poko-tests-without-k2/src/commonMain/kotlin/poko/AnyArrayHolder.kt
poko-tests-without-k2/src/commonMain/kotlin/poko/ArrayHolder.kt
poko-tests-without-k2/src/commonMain/kotlin/poko/ComplexGenericArrayHolder.kt
poko-tests-without-k2/src/commonMain/kotlin/poko/GenericArrayHolder.kt
poko-tests/src/commonMain/kotlin/poko/AnyArrayHolder.kt
poko-tests/src/commonMain/kotlin/poko/ArrayHolder.kt
poko-tests/src/commonMain/kotlin/poko/ComplexGenericArrayHolder.kt
poko-tests/src/commonMain/kotlin/poko/GenericArrayHolder.kt

This has been in used for awhile and doesn't seem to need changes.

Deprecate `@ArrayContentSupport` annotation

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt

There is an identical function in the compiler.
https://github.com/JetBrains/kotlin/blob/v2.0.20/compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/AdditionalIrUtils.kt#L22-L23

Remove isArrayOrPrimitiveArray() function

---

build-support/src/main/java/dev/drewhamilton/poko/build/PokoBuildPlugin.kt
poko-tests-without-k2/build.gradle.kts

Fixes this compiler warning:
```
w: '-progressive' is meaningful only for the latest language version (2.0), while this build uses 1.9
Compiler behavior in such mode is undefined; please, consider moving to the latest stable version or turning off progressive mode.
```

Disable progressive mode when using older language version

---

.github/workflows/ci.yml
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirExtensionSessionComponent.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
sample/buildSrc/settings.gradle.kts
sample/settings.gradle.kts

Tests compatibility of current Poko main branch with the new Kotlin beta version.

Test Kotlin 2.1.0-Beta2 in CI

---

.github/workflows/ci.yml
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt

The [fix](https://github.com/drewhamilton/Poko/pull/411#issuecomment-2420523314) that @JakeWharton found in #411 should allow compatibility with 2.0.0 to work after all.

Re-add sample tests against 2.0.0 and 2.0.10

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt

Too bad these are deprecated, they worked well for this use case.

Convert all context receivers to parameters

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirExtensionSessionComponent.kt

This public val has been available for awhile and is compatible across Kotlin versions.

Simplify cone type resolution in `PokoFirExtensionSessionComponent`

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt

Kotlin 2.1.0 broke ABI compatibility with older Kotlin versions (see #245), so internal workarounds to maintain compatibility are no longer needed.

Delete reflection and workarounds used to support Kotlin 2.0.x

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirCheckersExtension.kt

to work around compiler vs. IDE packaging issue.
I think this will address #428, but I'm having trouble verifying locally. The IDE keeps popping up the same error stacktrace, even though the `catch` is now in place. Maybe it's using some kind of caching mechanism, so I'm just going to try and merge this and see if it fixes the issue.

Use reflection-based `PsiElement` in error reporting 

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirCheckersExtension.kt

During multiplatform compilation, the experimental feature warning was logged even though the opt-in annotation was already in use. Apparently multiplatform `FqName`s use `.` instead of `/`.

Fix warning for non-custom `@Poko.Skip` annotation

---

poko-annotations/api/poko-annotations.api
poko-annotations/src/commonMain/kotlin/dev/drewhamilton/poko/ArrayContentBased.kt
poko-annotations/src/commonMain/kotlin/dev/drewhamilton/poko/Poko.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt
poko-tests-without-k2/src/commonMain/kotlin/poko/AnyArrayHolder.kt
poko-tests-without-k2/src/commonMain/kotlin/poko/ArrayHolder.kt
poko-tests-without-k2/src/commonMain/kotlin/poko/ComplexGenericArrayHolder.kt
poko-tests-without-k2/src/commonMain/kotlin/poko/GenericArrayHolder.kt
poko-tests/src/commonMain/kotlin/poko/AnyArrayHolder.kt
poko-tests/src/commonMain/kotlin/poko/ArrayHolder.kt
poko-tests/src/commonMain/kotlin/poko/ComplexGenericArrayHolder.kt
poko-tests/src/commonMain/kotlin/poko/GenericArrayHolder.kt

Inspired by [this discussion](https://github.com/drewhamilton/Poko/pull/446#discussion_r1880551600), this aligns with the location and tense of `@Poko.Skip` and allows for use of the array content-reading feature with a custom Poko annotation.

Rename `@ArrayContentBased` to `@Poko.ReadArrayContent`

---

build-support/src/main/java/dev/drewhamilton/poko/build/PokoBuildPlugin.kt

Replace `KotlinTopLevelExtensionConfig` with `KotlinBaseExtension` in `PokoBuildPlugin`

---

.github/workflows/ci.yml
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/compat.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt

Addresses the stacktrace filed in #455 and adds sample testing for the new beta version.

Kotlin 2.1.20-Beta1 support via reflection

---

build-support/src/main/java/dev/drewhamilton/poko/build/PokoBuildPlugin.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/CompilerOptions.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCommandLineProcessor.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-gradle-plugin/src/main/kotlin/dev/drewhamilton/poko/gradle/PokoGradlePlugin.kt

Passes a list of Gradle properties starting with "poko." to the Poko compiler plugin as additional arguments. The main goal of this is to allow adding temporary feature flags that don't have to remain permanently in the Gradle plugin's API. For example, #465 can temporarily go behind a `poko.experimental.enableFirGeneration` flag so it can be smoke tested in a few different contexts without affecting regular consumers.
Unknown flags trigger a warning and are then ignored.

Add support for property-based plugin arguments

---

poko-tests/src/commonTest/kotlin/AnyArrayHolderTest.kt
poko-tests/src/commonTest/kotlin/GenericArrayHolderTest.kt

Added noise to test output and would have resulted in an error in future Kotlin versions.

Fix warnings from reified intersection types in `:poko-tests`

---

.github/workflows/ci.yml

I'm curious about how much time each takes separately.
I'd also ideally like to trigger the sample build(s) after the "Upload MavenLocal directory" step completes, but that's not currently possible in GitHub Actions.

Separate build and test steps in CI

---

.github/workflows/ci.yml

Accidentally removed this in #469.

Make sure test-with-jdk CI job includes non-K2 testing

---

.github/workflows/ci.yml
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoFunction.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirDeclarationGenerationExtension.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirExtensionRegistrar.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoKey.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoFunctionBodyFiller.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoIrGenerationExtension.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/irHelpers.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-tests/build.gradle.kts

Previously, we only modified code at the IR layer; finding the `Any.equals`, `Any.hashCode`, and `Any.toString` functions, modifying their dispatch receiver to the Poko class and generating the body. With this change, when K2 is enabled, we instead generate these function declarations for each Poko class in FIR, and then (still) fill in the body in IR. This should make it possible for theoretical FIR-based linters to recognize that Poko classes have implemented these functions.
This new approach is hidden behind an experimental flag, `poko.experimental.enableFirDeclarationGeneration`, and is disabled by default. It should not be used in production yet.
~~Incidentally, this diverges from data classes, which do not declare these functions in FIR. I'm not sure if this is an intentional …

Generate Poko function declarations in FIR

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirDeclarationGenerationExtension.kt

This matches their modality in the current IR generation approach.

Make FIR-generated Poko functions open

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirDeclarationGenerationExtension.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-tests/src/commonMain/kotlin/poko/SuperclassWithFinalOverrides.kt
poko-tests/src/commonTest/kotlin/SuperclassWithFinalOverridesTest.kt

Fixes #471. Now, if a Poko class's superclass has a `final` override of any of the Poko functions, Poko does not generate an override of that function. Implemented for both the standard IR generation and the in-progress FIR generation.

Respect final Poko functions in superclass

---

poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-compiler-plugin/src/test/resources/api/DataInterface.kt

Tests the case raised in #492. Only works with FIR compilation. Does not appear to be easily fixable in non-FIR compilation, so I think I'll just enable FIR compilation by default soon.

Test compilation when superinterface declares abstract `equals` and `hashCode` functions

---

.github/workflows/ci.yml
.idea/kotlinc.xml
gradle/libs.versions.toml
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/compat.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/functionGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-tests/performance/src/test/kotlin/JsPerformanceTest.kt

Kotlin 2.1.20

---

.github/workflows/ci.yml
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/PokoCompilerPluginRegistrar.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoIrGenerationExtension.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-tests/build.gradle.kts

This has been tested for a few versions and appears to work fine. Fixes #492. Planning to merge after Kotlin 2.1.20 lands and cut a new release.

Enable FIR compilation by default

---

gradle/libs.versions.toml

I'm getting [weird errors](https://github.com/drewhamilton/Poko/actions/runs/14063119493/job/39446916085) publishing the latest release, and want to see whether it's the publish plugin causing them.

Revert to maven-publish-plugin 0.30.0

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirDeclarationGenerationExtension.kt
poko-tests/build.gradle.kts
poko-tests/src/commonMain/kotlin/poko/Expected.kt
poko-tests/src/commonTest/kotlin/ExpectedTest.kt
poko-tests/src/jsMain/kotlin/poko/Expected.js.kt
poko-tests/src/jvmMain/kotlin/poko/Expected.jvm.kt
poko-tests/src/nativeMain/kotlin/poko/Expected.native.kt
poko-tests/src/wasmJsMain/kotlin/poko/Expected.wasmJs.kt
poko-tests/src/wasmWasiMain/kotlin/poko/Expected.wasmWasi.kt

The `equals` function is implicitly an `operator fun` even though it is never explicitly written as such in source code. Omitting this keyword was causing compilation for `@Poko actual` classes to fail. Fixes #503.

Add `operator` keyword to generated `equals` FIR declaration

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/test/kotlin/dev/drewhamilton/poko/PokoCompilerPluginTest.kt
poko-compiler-plugin/src/test/resources/api/MultipleInterface.kt

Looks like a `filter` was missing between the logic in `PokoMembersTransform` and `PokoFirDeclarationGenerationExtension.kt`. Added a test which fails when compiling with the non-FIR mode, that then passes with 0129e131c42a8ad06641c563ba4fd1c058f673bd!
Closes #507

Filter on `ClassKind.CLASS` when resolving superclass under non-FIR compilation

---

.github/workflows/ci.yml
sample/build.gradle.kts

Since this language version now uses a different code path (non-FIR) than newer language versions, we must test both code paths against all supported Kotlin compilers.

Test sample builds with Kotlin language version 1.9

---

.github/workflows/ci.yml

Also roll back test of Kotlin 2.2.0-Beta2, which is failing, to 2.2.0-Beta1.

Test Kotlin 2.1.21-RC2

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt
poko-tests/src/commonTest/kotlin/ArrayHolderTest.kt
poko-tests/src/commonTest/kotlin/ComplexGenericArrayHolderTest.kt
poko-tests/src/commonTest/kotlin/GenericArrayHolderTest.kt

Discovered while working on #528 that `hashCode` and `toString` don't work properly for declared primitive arrays on the NodeJS target.
The `toString` problem is evident in the generated .js file; `contentToString` is not used for primitive arrays. The Poko code comment "Primitive arrays don't need deep toString" appears to be true for all platforms _except_ NodeJS, for some reason, but is quickly fixed by removing the associated `if` statement.
The `hashCode` problem is less evident, as it does appear to be using `contentHashCode`, and at a glance the [JS implementation](https://github.com/JetBrains/kotlin/blob/v2.1.20/libraries/stdlib/js/runtime/collectionsHacks.kt#L50-L61) looks the same as the JVM implementation. Not sure that it's very important for `hashCode` to match across …

Fix NodeJS array content handling

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/compat.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/toStringGeneration.kt
sample/mpp/src/commonMain/kotlin/dev/drewhamilton/poko/sample/mpp/ArraysSample.kt
sample/mpp/src/commonTest/kotlin/dev/drewhamilton/poko/sample/mpp/ArraysSampleTest.kt

These code paths were missed in all the cross-version tests, so some failures that should have been caught by #527 weren't caught.

Add arrays sample to `:mpp` sample project

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/PokoMembersTransformer.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/compat.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/equalsGeneration.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt

This API is introduced in 2.1.20 and required in 2.2.x. See https://github.com/JetBrains/kotlin/blob/master/docs/backend/IR_parameter_api_migration.md.

Use new `IrFunction.parameters` property

---

build-support/src/main/java/dev/drewhamilton/poko/build/PokoBuildPlugin.kt

The old portal is being [shut down](https://central.sonatype.org/news/20250326_ossrh_sunset/).

Update publishing to Sonatype Central Portal

---

.github/workflows/ci.yml
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirDeclarationGenerationExtension.kt
poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/compat.kt

Adds forward compatibility with the changed signature for the FIR `isExtension` extension. Addresses the initial problem mentioned in #561.

Test Kotlin 2.20.0-Beta1

---

poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirDeclarationGenerationExtension.kt

Missed this in #563. Should fix the issues with Mosaic and Metro mentioned in comments on #561.

Replace remaining `isExtension` call site with `isExtensionCompat`

---

sample/gradle.properties

Enabling the metadata version check will stop allowing loading of classes with bad metadata versions or pre-release classes.
This should stop #557 recurring. Test by bumping this to 2.2 or 2.3 then building the sample project - it should now fail:
https://github.com/drewhamilton/Poko/blob/1231efdf533a25a0b5383bbeaef91453d167eaa0/poko-gradle-plugin/build.gradle.kts#L14-L15

Enable Kotlin metadata version check in sample project

---

sample/build.gradle.kts
sample/buildSrc/src/main/kotlin/dev/drewhamilton/poko/sample/build/java.kt
sample/compose/build.gradle.kts
sample/settings.gradle.kts

Replace deprecated APIs with non-deprecated ones. Drop logic around varying Java versions for testing, which we don't use anymore in the sample project. Bump Android sample to compile with Android SDK 36.

Update sample project Gradle scripts
